-- Generated by Matugen
local M = {}

M.colors = {
  background       = "{{colors.background.dark.hex}}",
  surface_lowest   = "{{colors.surface_container_lowest.dark.hex}}",
  surface_low      = "{{colors.surface_container_low.dark.hex}}",
  surface          = "{{colors.surface.dark.hex}}",
  surface_container= "{{colors.surface_container.dark.hex}}",
  surface_high     = "{{colors.surface_container_high.dark.hex}}",
  surface_highest  = "{{colors.surface_container_highest.dark.hex}}",
  surface_bright   = "{{colors.surface_bright.dark.hex}}",
  surface_variant  = "{{colors.surface_variant.dark.hex}}",
  on_surface       = "{{colors.on_surface.dark.hex}}",
  on_surface_var   = "{{colors.on_surface_variant.dark.hex}}",
  outline          = "{{colors.outline.dark.hex}}",
  outline_variant  = "{{colors.outline_variant.dark.hex}}",
  primary          = "{{colors.primary.dark.hex}}",
  on_primary       = "{{colors.on_primary.dark.hex}}",
  primary_container= "{{colors.primary_container.dark.hex}}",
  on_primary_cont  = "{{colors.on_primary_container.dark.hex}}",
  inverse_primary  = "{{colors.inverse_primary.dark.hex}}",
  secondary        = "{{colors.secondary.dark.hex}}",
  on_secondary     = "{{colors.on_secondary.dark.hex}}",
  secondary_container = "{{colors.secondary_container.dark.hex}}",
  on_secondary_cont= "{{colors.on_secondary_container.dark.hex}}",
  tertiary         = "{{colors.tertiary.dark.hex}}",
  on_tertiary      = "{{colors.on_tertiary.dark.hex}}",
  tertiary_container  = "{{colors.tertiary_container.dark.hex}}",
  on_tertiary_cont = "{{colors.on_tertiary_container.dark.hex}}",
  tertiary_fixed_dim = "{{colors.tertiary_fixed_dim.dark.hex}}",
  error            = "{{colors.error.dark.hex}}",
  on_error         = "{{colors.on_error.dark.hex}}",
  error_container  = "{{colors.error_container.dark.hex}}",
  on_error_cont    = "{{colors.on_error_container.dark.hex}}",
}

function M.apply()
  local c = M.colors
  vim.cmd("highlight clear")
  vim.o.termguicolors = true
  vim.o.background = "dark"
  vim.g.colors_name = "matugen"

  local hl = vim.api.nvim_set_hl

  -- Editor chrome
  hl(0, "Normal",          { fg = c.on_surface,       bg = c.background })
  hl(0, "NormalFloat",     { fg = c.on_surface,        bg = c.surface_container })
  hl(0, "NormalNC",        { fg = c.on_surface,        bg = c.background })
  hl(0, "ColorColumn",     { bg = c.surface_container })
  hl(0, "Cursor",          { fg = c.background,        bg = c.primary })
  hl(0, "CursorLine",      { bg = c.surface_container })
  hl(0, "CursorLineNr",    { fg = c.primary,           bold = true })
  hl(0, "LineNr",          { fg = c.on_surface_var })
  hl(0, "SignColumn",      { bg = c.background })
  hl(0, "StatusLine",      { fg = c.on_surface,        bg = c.surface_container })
  hl(0, "StatusLineNC",    { fg = c.on_surface_var,    bg = c.surface })
  hl(0, "TabLine",         { fg = c.on_surface_var,    bg = c.surface })
  hl(0, "TabLineFill",     { bg = c.background })
  hl(0, "TabLineSel",      { fg = c.on_primary,        bg = c.primary })
  hl(0, "WinSeparator",    { fg = c.surface_variant,   bg = c.background })
  hl(0, "EndOfBuffer",     { fg = c.background,        bg = c.background })
  hl(0, "FloatBorder",     { fg = c.outline,           bg = c.surface_container })
  hl(0, "Pmenu",           { fg = c.on_surface,        bg = c.surface_container })
  hl(0, "PmenuSel",        { fg = c.on_primary_cont,   bg = c.primary_container })
  hl(0, "PmenuSbar",       { bg = c.surface_highest })
  hl(0, "PmenuThumb",      { bg = c.primary })
  hl(0, "Visual",          { fg = c.on_primary_cont,   bg = c.primary_container })
  hl(0, "Search",          { fg = c.on_primary_cont,   bg = c.primary_container })
  hl(0, "IncSearch",       { fg = c.on_primary,        bg = c.primary })
  hl(0, "MatchParen",      { fg = c.tertiary,          bold = true })
  hl(0, "NonText",         { fg = c.outline_variant })
  hl(0, "SpecialKey",      { fg = c.outline_variant })
  hl(0, "Folded",          { fg = c.on_surface_var,    bg = c.surface_container })
  hl(0, "Title",           { fg = c.primary,           bold = true })
  hl(0, "Directory",       { fg = c.secondary })

  -- Syntax
  hl(0, "Comment",         { fg = c.outline,           italic = true })
  hl(0, "Constant",        { fg = c.tertiary })
  hl(0, "String",          { fg = c.tertiary_fixed_dim })
  hl(0, "Number",          { fg = c.tertiary })
  hl(0, "Boolean",         { fg = c.tertiary })
  hl(0, "Identifier",      { fg = c.on_surface })
  hl(0, "Function",        { fg = c.secondary })
  hl(0, "Statement",       { fg = c.primary,           bold = true })
  hl(0, "Keyword",         { fg = c.inverse_primary,   bold = true })
  hl(0, "Operator",        { fg = c.on_surface_var })
  hl(0, "PreProc",         { fg = c.secondary })
  hl(0, "Type",            { fg = c.tertiary })
  hl(0, "Special",         { fg = c.secondary })
  hl(0, "Underlined",      { underline = true })
  hl(0, "Error",           { fg = c.error })
  hl(0, "Todo",            { fg = c.on_primary_cont,   bg = c.primary_container, bold = true })

  -- Diagnostics
  hl(0, "DiagnosticError",            { fg = c.error })
  hl(0, "DiagnosticWarn",             { fg = c.tertiary })
  hl(0, "DiagnosticInfo",             { fg = c.secondary })
  hl(0, "DiagnosticHint",             { fg = c.on_surface_var })
  hl(0, "DiagnosticUnderlineError",   { sp = c.error,    underline = true })
  hl(0, "DiagnosticUnderlineWarn",    { sp = c.tertiary, underline = true })

  -- Treesitter
  hl(0, "@comment",           { link = "Comment" })
  hl(0, "@string",            { link = "String" })
  hl(0, "@string.escape",     { fg = c.tertiary,          bg = c.tertiary_container })
  hl(0, "@number",            { link = "Number" })
  hl(0, "@boolean",           { link = "Boolean" })
  hl(0, "@function",          { link = "Function" })
  hl(0, "@function.call",     { fg = c.secondary })
  hl(0, "@keyword",           { link = "Keyword" })
  hl(0, "@type",              { link = "Type" })
  hl(0, "@variable",          { fg = c.on_surface })
  hl(0, "@property",          { fg = c.secondary })
  hl(0, "@operator",          { link = "Operator" })
  hl(0, "@punctuation",       { fg = c.on_surface_var })
  hl(0, "TSMethod",           { fg = c.tertiary })
  hl(0, "TSFunction",         { fg = c.secondary })
  hl(0, "TSComment",          { fg = c.outline,           italic = true })
end

return M
