-- Generated by Matugen
local M = {}

M.colors = {
  background       = "#141218",
  surface_lowest   = "#0f0d13",
  surface_low      = "#1d1b20",
  surface          = "#141218",
  surface_container= "#211f24",
  surface_high     = "#2b292f",
  surface_highest  = "#36343a",
  surface_bright   = "#3b383e",
  surface_variant  = "#49454e",
  on_surface       = "#e7e0e8",
  on_surface_var   = "#cbc4cf",
  outline          = "#948f99",
  outline_variant  = "#49454e",
  primary          = "#d1bcfd",
  on_primary       = "#38265c",
  primary_container= "#4f3d75",
  on_primary_cont  = "#eaddff",
  inverse_primary  = "#67558e",
  secondary        = "#ccc2db",
  on_secondary     = "#342d41",
  secondary_container = "#4a4358",
  on_secondary_cont= "#e9def8",
  tertiary         = "#f0b8c6",
  on_tertiary      = "#4a2531",
  tertiary_container  = "#643b47",
  on_tertiary_cont = "#ffd9e1",
  tertiary_fixed_dim = "#f0b8c6",
  error            = "#ffb4ab",
  on_error         = "#690005",
  error_container  = "#93000a",
  on_error_cont    = "#ffdad6",
}

function M.apply()
  local c = M.colors
  vim.cmd("highlight clear")
  vim.o.termguicolors = true
  vim.o.background = "dark"
  vim.g.colors_name = "matugen"

  local hl = vim.api.nvim_set_hl

  -- Editor chrome
  hl(0, "Normal",          { fg = c.on_surface,       bg = c.background })
  hl(0, "NormalFloat",     { fg = c.on_surface,        bg = c.surface_container })
  hl(0, "NormalNC",        { fg = c.on_surface,        bg = c.background })
  hl(0, "ColorColumn",     { bg = c.surface_container })
  hl(0, "Cursor",          { fg = c.background,        bg = c.primary })
  hl(0, "CursorLine",      { bg = c.surface_container })
  hl(0, "CursorLineNr",    { fg = c.primary,           bold = true })
  hl(0, "LineNr",          { fg = c.on_surface_var })
  hl(0, "SignColumn",      { bg = c.background })
  hl(0, "StatusLine",      { fg = c.on_surface,        bg = c.surface_container })
  hl(0, "StatusLineNC",    { fg = c.on_surface_var,    bg = c.surface })
  hl(0, "TabLine",         { fg = c.on_surface_var,    bg = c.surface })
  hl(0, "TabLineFill",     { bg = c.background })
  hl(0, "TabLineSel",      { fg = c.on_primary,        bg = c.primary })
  hl(0, "WinSeparator",    { fg = c.surface_variant,   bg = c.background })
  hl(0, "EndOfBuffer",     { fg = c.background,        bg = c.background })
  hl(0, "FloatBorder",     { fg = c.outline,           bg = c.surface_container })
  hl(0, "Pmenu",           { fg = c.on_surface,        bg = c.surface_container })
  hl(0, "PmenuSel",        { fg = c.on_primary_cont,   bg = c.primary_container })
  hl(0, "PmenuSbar",       { bg = c.surface_highest })
  hl(0, "PmenuThumb",      { bg = c.primary })
  hl(0, "Visual",          { fg = c.on_primary_cont,   bg = c.primary_container })
  hl(0, "Search",          { fg = c.on_primary_cont,   bg = c.primary_container })
  hl(0, "IncSearch",       { fg = c.on_primary,        bg = c.primary })
  hl(0, "MatchParen",      { fg = c.tertiary,          bold = true })
  hl(0, "NonText",         { fg = c.outline_variant })
  hl(0, "SpecialKey",      { fg = c.outline_variant })
  hl(0, "Folded",          { fg = c.on_surface_var,    bg = c.surface_container })
  hl(0, "Title",           { fg = c.primary,           bold = true })
  hl(0, "Directory",       { fg = c.secondary })

  -- Syntax
  hl(0, "Comment",         { fg = c.outline,           italic = true })
  hl(0, "Constant",        { fg = c.tertiary })
  hl(0, "String",          { fg = c.tertiary_fixed_dim })
  hl(0, "Number",          { fg = c.tertiary })
  hl(0, "Boolean",         { fg = c.tertiary })
  hl(0, "Identifier",      { fg = c.on_surface })
  hl(0, "Function",        { fg = c.secondary })
  hl(0, "Statement",       { fg = c.primary,           bold = true })
  hl(0, "Keyword",         { fg = c.inverse_primary,   bold = true })
  hl(0, "Operator",        { fg = c.on_surface_var })
  hl(0, "PreProc",         { fg = c.secondary })
  hl(0, "Type",            { fg = c.tertiary })
  hl(0, "Special",         { fg = c.secondary })
  hl(0, "Underlined",      { underline = true })
  hl(0, "Error",           { fg = c.error })
  hl(0, "Todo",            { fg = c.on_primary_cont,   bg = c.primary_container, bold = true })

  -- Diagnostics
  hl(0, "DiagnosticError",            { fg = c.error })
  hl(0, "DiagnosticWarn",             { fg = c.tertiary })
  hl(0, "DiagnosticInfo",             { fg = c.secondary })
  hl(0, "DiagnosticHint",             { fg = c.on_surface_var })
  hl(0, "DiagnosticUnderlineError",   { sp = c.error,    underline = true })
  hl(0, "DiagnosticUnderlineWarn",    { sp = c.tertiary, underline = true })

  -- Treesitter
  hl(0, "@comment",           { link = "Comment" })
  hl(0, "@string",            { link = "String" })
  hl(0, "@string.escape",     { fg = c.tertiary,          bg = c.tertiary_container })
  hl(0, "@number",            { link = "Number" })
  hl(0, "@boolean",           { link = "Boolean" })
  hl(0, "@function",          { link = "Function" })
  hl(0, "@function.call",     { fg = c.secondary })
  hl(0, "@keyword",           { link = "Keyword" })
  hl(0, "@type",              { link = "Type" })
  hl(0, "@variable",          { fg = c.on_surface })
  hl(0, "@property",          { fg = c.secondary })
  hl(0, "@operator",          { link = "Operator" })
  hl(0, "@punctuation",       { fg = c.on_surface_var })
  hl(0, "TSMethod",           { fg = c.tertiary })
  hl(0, "TSFunction",         { fg = c.secondary })
  hl(0, "TSComment",          { fg = c.outline,           italic = true })
end

return M
