[config]

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/kitty.conf"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.conf"
output_path = "~/.config/hypr/hyprland.conf"

[templates.starship]
input_path = "~/.config/matugen/templates/starship.toml"
output_path = "~/.config/starship.toml"

[templates.claude-theme]
input_path = "~/.config/matugen/templates/claude-theme.json"
output_path = "~/.claude/themes/mytheme.json"

[templates.fastfetch]
input_path = "~/.config/matugen/templates/fastfetch.jsonc"
output_path = "~/.config/fastfetch/config.jsonc"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/style.css"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprlock.conf"
output_path = "~/.config/hypr/hyprlock.conf"

[templates.neovim]
input_path = "~/.config/matugen/templates/neovim-colors.lua"
output_path = "~/.config/nvim/lua/colors/matugen.lua"

[templates.wofi]
input_path = "~/.config/matugen/templates/wofi.css"
output_path = "~/.config/wofi/style.css"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-3.0/colors.css"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-4.0/colors.css"

# config_directory/config.toml
[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "any"]
set = true
# pre_hook = ""
post_hook = "killall waybar; waybar & killall swaync; swaync &"
